Repository wecode-bootcamp-korea/37-1st-HUSH-frontend, pull requests merged in 2022-09, with the labels that each got.

#5 [37기 주혜린] Refactor : 회원가입 페이지 수정 요청 사항 반영 완료
  .eslintrc
  src/pages/Join/Join.js
  src/pages/Join/Join.scss
Labels: 완료

#13 37기 주혜린] Refactor : 로그인 페이지 수정 요청 사항 반영
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#8 [37기 김대호] Add : Nav 컴포넌트 레이아웃 구현 및 추가 구현사항 진행중
  public/images/Nav/basket.png
  public/images/Nav/choco.jpeg
  public/images/Nav/heart.png
  public/images/Nav/heartHover.png
  public/images/Nav/login.png
  public/images/Nav/loginClick.png
  public/images/Nav/search.png
  public/images/Nav/test.mp4
  public/images/test.jpg
  src/Router.js
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
  src/components/nav/NavModal.js
  src/components/nav/NavModal.scss
  src/components/nav/SearchModal.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: 수정 요청

#12 [37기 주혜린] Fix : 장바구니 페이지 수정 요청 사항 반영
  public/data/cart.json
  public/images/like/sad.png
  src/asset/images/cart_add.png
  src/asset/images/cart_add_hover.png
  src/asset/images/cart_minus.png
  src/asset/images/cart_minus_hover.png
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartProduct.js
  src/pages/Cart/CartProduct.scss
  src/pages/myPage/MyPage.js
Labels: 멘토 리뷰 요청

#14 [37기 김대호] Add : common 공용 파일 정리, 추가 페이지, 라우터 설정 완료
  public/data/products.json
  public/data/slider.json
  public/data/users.json
  public/images/cusCakes.jpg
  public/images/detail/heart.png
  public/images/detail/minus_ico.png
  public/images/detail/plus_ico.png
  public/images/main/banner1.avif
  public/images/main/banner2.avif
  public/images/main/cake1.jpeg
  public/images/main/cake1_1.jpeg
  public/images/main/candy1.jpeg
  public/images/main/candy1_1.jpeg
  public/images/main/chocolate1.jpeg
  public/images/main/chocolate1_1.jpeg
  public/images/main/cookie1.jpeg
  public/images/main/cookie1_1.jpeg
  public/images/main/jelly1.jpeg
  public/images/main/jelly1_1.jpeg
  public/images/main/main_visual1.jpg
  public/images/main/main_visual2.jpg
  public/images/main/main_visual3.jpg
  public/images/sub/00.메인페이지.png
  public/images/sub/01.회원가입페이지.png
  public/images/sub/02.로그인페이지.png
  public/images/sub/03.제품페이지.png
  public/images/sub/04.장바구니페이지.png
  public/images/sub/05.상세페이지.png
  public/images/sub/06.결제페이지.png
  public/images/sub/team.jpeg
  public/images/sub/team.jpg
  public/index.html
  src/Router.js
  src/ScrollToTop.js
  src/asset/font/Lush.woff
  src/index.js
  src/pages/sub/Event.js
  src/pages/sub/Event.scss
  src/pages/sub/Intro.js
  src/pages/sub/Intro.scss
  src/pages/sub/Store.js
  src/pages/sub/Store.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: Conflict 해결 요청

#11 [37기 강루비] Add: 상세페이지 - 리뷰 작성, 이메일 마스킹, 오늘 날짜 작업
  .eslintrc
  public/data/all.json
  public/data/review.json
  src/hooks/useScrollFadeIn.js
  src/pages/detailPage/Detail.js
  src/pages/detailPage/Detail.scss
  src/pages/detailPage/DetailPrdInfo.js
  src/pages/detailPage/DetailPrdInfo.scss
  src/pages/detailPage/DetailPrdReview.js
  src/pages/detailPage/DetailPrdReview.scss
  src/pages/detailPage/DetailReviewList.js
  src/pages/detailPage/DetailReviewList.scss
  src/pages/detailPage/DetailTab.js
  src/pages/detailPage/DetailTab.scss
  src/pages/detailPage/DetailTopInfo.js
  src/pages/main/Banner.js
  src/pages/main/Banner.scss
  src/pages/main/Main.js
  src/pages/main/Main.scss
  src/pages/main/Review.js
  src/pages/main/Review.scss
  src/pages/main/Slider.js
  src/pages/main/Slider.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#2 [37기 양석문] Product conflict 수정 완료
  .eslintrc
  public/data/all.json
  public/data/users.json
  public/data/젤리.json
  public/data/초콜릿.json
  public/data/캔디.json
  public/data/케이크.json
  public/data/쿠키.json
  public/images/cup.jpg
  public/images/downArrow.png
  public/images/heart.png
  public/images/minus_ico.png
  public/images/plus_ico.png
  public/index.html
  src/font/Lush.woff
  src/pages/ProductPage/Product.js
  src/pages/ProductPage/Product.scss
  src/pages/ProductPage/ProductDropdown.js
  src/pages/ProductPage/ProductList.js
  src/pages/ProductPage/ProductList.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#16 [37기 양석문] fix: eslint 불필요한 내용 삭제
  .eslintrc
Labels: 멘토 리뷰 요청
